# Assignment 2: Spam Email Detection Using NLP

Name: Muhammad Zeeshan

Roll Number: SU92-BSSEM-S25-041

Course: AI-Theory

In [2]:
import sys
import pandas as pd
import numpy as np

print("Python version:", sys.version)
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Environment is ready!")

Python version: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
Pandas version: 2.2.3
NumPy version: 2.1.3
Environment is ready!

In [4]:
# Create a dataset of 10 email messages

data = {
    "label": [
        "Spam", "Ham", "Spam", "Ham", "Spam",
        "Ham", "Spam", "Ham", "Spam", "Ham"
    ],
    "message": [
        "Congratulations! You have won a free prize.",
        "Your assignment deadline is Friday. Please submit it on time.",
        "Get a free mobile phone now.",
        "Your class will start tomorrow at 9 AM.",
        "Claim your free gift card before the offer expires.",
        "Please find the lecture notes attached.",
        "You have won a cash lottery.",
        "Thank you for attending the meeting.",
        "Congratulations! Claim your free reward now.",
        "Please share your feedback."
    ]
}

print("Dataset created successfully!")

Dataset created successfully!

In [5]:
# Convert the dataset into a Pandas DataFrame

df = pd.DataFrame(data)

# Display the complete dataset
display(df)

  label                                            message
0  Spam        Congratulations! You have won a free prize.
1   Ham  Your assignment deadline is Friday. Please sub...
2  Spam                       Get a free mobile phone now.
3   Ham            Your class will start tomorrow at 9 AM.
4  Spam  Claim your free gift card before the offer exp...
5   Ham            Please find the lecture notes attached.
6  Spam                       You have won a cash lottery.
7   Ham               Thank you for attending the meeting.
8  Spam       Congratulations! Claim your free reward now.
9   Ham                        Please share your feedback.

In [6]:
# Count the number of emails in each category

print("Total emails:", len(df))
print("\nEmail category counts:")
print(df["label"].value_counts())

Total emails: 10

Email category counts:
label
Spam    5
Ham     5
Name: count, dtype: int64

In [7]:
# 1. Display the first five rows
print("1. First five rows:")
display(df.head())

# 2. Display the number of rows and columns
print("2. Dataset shape:")
print(df.shape)

# 3. Display dataset information
print("3. Dataset information:")
df.info()

1. First five rows:

  label                                            message
0  Spam        Congratulations! You have won a free prize.
1   Ham  Your assignment deadline is Friday. Please sub...
2  Spam                       Get a free mobile phone now.
3   Ham            Your class will start tomorrow at 9 AM.
4  Spam  Claim your free gift card before the offer exp...

2. Dataset shape:
(10, 2)
3. Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    10 non-null     object
 1   message  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [8]:
# Step 1: Lowercasing

df["lower_text"] = df["message"].str.lower()

# Display original and lowercase messages
display(df[["message", "lower_text"]].head(10))

,message,lower_text
0,Congratulations! You have won a free prize.,congratulations! you have won a free prize.
1,Your assignment deadline is Friday. Please sub...,your assignment deadline is friday. please sub...
2,Get a free mobile phone now.,get a free mobile phone now.
3,Your class will start tomorrow at 9 AM.,your class will start tomorrow at 9 am.
4,Claim your free gift card before the offer exp...,claim your free gift card before the offer exp...
5,Please find the lecture notes attached.,please find the lecture notes attached.
6,You have won a cash lottery.,you have won a cash lottery.
7,Thank you for attending the meeting.,thank you for attending the meeting.
8,Congratulations! Claim your free reward now.,congratulations! claim your free reward now.
9,Please share your feedback.,please share your feedback.

In [9]:
# Install NLTK if needed
%pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)

In [10]:
import nltk
from nltk.tokenize import word_tokenize

# Download tokenizer data
nltk.download("punkt")
nltk.download("punkt_tab")

# Tokenize the lowercase messages
df["tokens"] = df["lower_text"].apply(word_tokenize)

# Display the results
display(df[["lower_text", "tokens"]].head(10))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,lower_text,tokens
0,congratulations! you have won a free prize.,"[congratulations, !, you, have, won, a, free, ..."
1,your assignment deadline is friday. please sub...,"[your, assignment, deadline, is, friday, ., pl..."
2,get a free mobile phone now.,"[get, a, free, mobile, phone, now, .]"
3,your class will start tomorrow at 9 am.,"[your, class, will, start, tomorrow, at, 9, am..."
4,claim your free gift card before the offer exp...,"[claim, your, free, gift, card, before, the, o..."
5,please find the lecture notes attached.,"[please, find, the, lecture, notes, attached, .]"
6,you have won a cash lottery.,"[you, have, won, a, cash, lottery, .]"
7,thank you for attending the meeting.,"[thank, you, for, attending, the, meeting, .]"
8,congratulations! claim your free reward now.,"[congratulations, !, claim, your, free, reward..."
9,please share your feedback.,"[please, share, your, feedback, .]"

In [11]:
nltk.download("stopwords")

from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

# Remove stop words and punctuation tokens
df["tokens_no_stopwords"] = df["tokens"].apply(
    lambda tokens: [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]
)

# Display the results
display(df[["tokens", "tokens_no_stopwords"]].head(10))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,tokens,tokens_no_stopwords
0,"[congratulations, !, you, have, won, a, free, ...","[congratulations, free, prize]"
1,"[your, assignment, deadline, is, friday, ., pl...","[assignment, deadline, friday, please, submit,..."
2,"[get, a, free, mobile, phone, now, .]","[get, free, mobile, phone]"
3,"[your, class, will, start, tomorrow, at, 9, am...","[class, start, tomorrow]"
4,"[claim, your, free, gift, card, before, the, o...","[claim, free, gift, card, offer, expires]"
5,"[please, find, the, lecture, notes, attached, .]","[please, find, lecture, notes, attached]"
6,"[you, have, won, a, cash, lottery, .]","[cash, lottery]"
7,"[thank, you, for, attending, the, meeting, .]","[thank, attending, meeting]"
8,"[congratulations, !, claim, your, free, reward...","[congratulations, claim, free, reward]"
9,"[please, share, your, feedback, .]","[please, share, feedback]"

In [12]:
print("Code is running successfully!")

Code is running successfully!

In [14]:
# Text Preprocessing: Lowercasing, Tokenization, Stop Word Removal

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download required NLTK resources
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

# 1. Lowercasing
df["lower_text"] = df["message"].str.lower()

# 2. Tokenization
df["tokens"] = df["lower_text"].apply(word_tokenize)

# 3. Stop Word Removal
stop_words = set(stopwords.words("english"))

df["tokens_no_stopwords"] = df["tokens"].apply(
    lambda tokens: [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]
)

# Display the results
display(
    df[["message", "lower_text", "tokens", "tokens_no_stopwords"]]
)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,message,lower_text,tokens,tokens_no_stopwords
0,Congratulations! You have won a free prize.,congratulations! you have won a free prize.,"[congratulations, !, you, have, won, a, free, ...","[congratulations, free, prize]"
1,Your assignment deadline is Friday. Please sub...,your assignment deadline is friday. please sub...,"[your, assignment, deadline, is, friday, ., pl...","[assignment, deadline, friday, please, submit,..."
2,Get a free mobile phone now.,get a free mobile phone now.,"[get, a, free, mobile, phone, now, .]","[get, free, mobile, phone]"
3,Your class will start tomorrow at 9 AM.,your class will start tomorrow at 9 am.,"[your, class, will, start, tomorrow, at, 9, am...","[class, start, tomorrow]"
4,Claim your free gift card before the offer exp...,claim your free gift card before the offer exp...,"[claim, your, free, gift, card, before, the, o...","[claim, free, gift, card, offer, expires]"
5,Please find the lecture notes attached.,please find the lecture notes attached.,"[please, find, the, lecture, notes, attached, .]","[please, find, lecture, notes, attached]"
6,You have won a cash lottery.,you have won a cash lottery.,"[you, have, won, a, cash, lottery, .]","[cash, lottery]"
7,Thank you for attending the meeting.,thank you for attending the meeting.,"[thank, you, for, attending, the, meeting, .]","[thank, attending, meeting]"
8,Congratulations! Claim your free reward now.,congratulations! claim your free reward now.,"[congratulations, !, claim, your, free, reward...","[congratulations, claim, free, reward]"
9,Please share your feedback.,please share your feedback.,"[please, share, your, feedback, .]","[please, share, feedback]"

In [15]:
# Step 4: Stemming and Step 5: Lemmatization

from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Apply stemming
df["stemmed_words"] = df["tokens_no_stopwords"].apply(
    lambda tokens: [stemmer.stem(word) for word in tokens]
)

# Apply lemmatization
df["lemmatized_words"] = df["tokens_no_stopwords"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

# Display results
display(
    df[[
        "message",
        "tokens_no_stopwords",
        "stemmed_words",
        "lemmatized_words"
    ]]
)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

,message,tokens_no_stopwords,stemmed_words,lemmatized_words
0,Congratulations! You have won a free prize.,"[congratulations, free, prize]","[congratul, free, prize]","[congratulation, free, prize]"
1,Your assignment deadline is Friday. Please sub...,"[assignment, deadline, friday, please, submit,...","[assign, deadlin, friday, pleas, submit, time]","[assignment, deadline, friday, please, submit,..."
2,Get a free mobile phone now.,"[get, free, mobile, phone]","[get, free, mobil, phone]","[get, free, mobile, phone]"
3,Your class will start tomorrow at 9 AM.,"[class, start, tomorrow]","[class, start, tomorrow]","[class, start, tomorrow]"
4,Claim your free gift card before the offer exp...,"[claim, free, gift, card, offer, expires]","[claim, free, gift, card, offer, expir]","[claim, free, gift, card, offer, expires]"
5,Please find the lecture notes attached.,"[please, find, lecture, notes, attached]","[pleas, find, lectur, note, attach]","[please, find, lecture, note, attached]"
6,You have won a cash lottery.,"[cash, lottery]","[cash, lotteri]","[cash, lottery]"
7,Thank you for attending the meeting.,"[thank, attending, meeting]","[thank, attend, meet]","[thank, attending, meeting]"
8,Congratulations! Claim your free reward now.,"[congratulations, claim, free, reward]","[congratul, claim, free, reward]","[congratulation, claim, free, reward]"
9,Please share your feedback.,"[please, share, feedback]","[pleas, share, feedback]","[please, share, feedback]"

In [16]:
# Bag of Words (BoW) Feature Extraction

from sklearn.feature_extraction.text import CountVectorizer

# Convert cleaned tokens back into sentences
df["processed_text"] = df["lemmatized_words"].apply(
    lambda words: " ".join(words)
)

# Create Bag of Words vectors
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(df["processed_text"])

# Display vocabulary
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

# Display numerical matrix
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print("\nBag of Words Matrix:")
display(bow_df)

Vocabulary:
['assignment' 'attached' 'attending' 'card' 'cash' 'claim' 'class'
 'congratulation' 'deadline' 'expires' 'feedback' 'find' 'free' 'friday'
 'get' 'gift' 'lecture' 'lottery' 'meeting' 'mobile' 'note' 'offer'
 'phone' 'please' 'prize' 'reward' 'share' 'start' 'submit' 'thank' 'time'
 'tomorrow']

Bag of Words Matrix:

,assignment,attached,attending,card,cash,claim,class,congratulation,deadline,expires,...,phone,please,prize,reward,share,start,submit,thank,time,tomorrow
0,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0

In [18]:
%pip install -q sentence-transformers

In [19]:
# Step 6: Generate Semantic Vector Embeddings

from sentence_transformers import SentenceTransformer
import pandas as pd

# Load a pretrained embedding model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Use the original email messages
messages = df["message"].tolist()

# Generate one embedding vector for each email
embeddings = model.encode(messages)

# Display the embedding matrix dimensions
print("Number of email messages:", len(messages))
print("Embedding matrix shape:", embeddings.shape)

# Display the first email and its embedding
print("\nFirst email:")
print(messages[0])

print("\nFirst 10 values of its embedding:")
print(embeddings[0][:10])

# Display a preview of the embedding matrix
embedding_df = pd.DataFrame(
    embeddings,
    index=[f"Email {i+1}" for i in range(len(messages))]
)

print("\nEmbedding matrix preview:")
display(embedding_df.iloc[:, :10])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Number of email messages: 10
Embedding matrix shape: (10, 384)

First email:
Congratulations! You have won a free prize.

First 10 values of its embedding:
[-0.04286236  0.04470446  0.01103477  0.04554786  0.01032125  0.04568583
  0.03645185 -0.04928138 -0.05980798  0.00150082]

Embedding matrix preview:

,0,1,2,3,4,5,6,7,8,9
Email 1,-0.042862,0.044704,0.011035,0.045548,0.010321,0.045686,0.036452,-0.049281,-0.059808,0.001501
Email 2,-0.062948,0.062965,-0.016151,-0.009171,0.010431,-0.041878,-0.021588,0.002838,-0.116137,0.006957
Email 3,-0.034817,0.014303,0.139398,-0.024143,0.030147,-0.014429,-0.027990,0.033806,0.044722,0.029038
Email 4,-0.061452,-0.032167,0.001085,-0.009234,-0.015119,0.022941,-0.078902,0.045886,-0.077117,-0.005879
Email 5,-0.088055,0.068895,0.058706,0.039981,0.029565,0.047461,0.040300,-0.009249,0.076063,0.015503
Email 6,-0.103257,0.017275,-0.032672,0.000023,-0.007448,0.024034,-0.062740,0.074878,-0.085650,0.012285
Email 7,-0.025800,0.016851,0.047656,-0.004265,-0.046429,-0.007650,0.143130,-0.017264,-0.017656,-0.013386
Email 8,0.017291,0.056612,0.038882,0.027361,0.001053,0.011881,0.033994,-0.048593,-0.062455,-0.025224
Email 9,-0.061059,0.052409,-0.006262,0.007601,0.053015,0.082398,0.014684,-0.000116,-0.052430,0.056235
Email 10,0.003928,-0.001169,0.007746,-0.083043,0.031620,0.009880,-0.105249,-0.000528,0.038580,0.009745

In [20]:
# Save all embedding values in a CSV file
embedding_results = pd.DataFrame(embeddings)
embedding_results.insert(0, "label", df["label"])
embedding_results.insert(1, "message", df["message"])

embedding_results.to_csv("email_embeddings.csv", index=False)

print("Embedding results saved successfully.")
display(embedding_results.head())

Embedding results saved successfully.

,label,message,0,1,2,3,4,5,6,7,...,374,375,376,377,378,379,380,381,382,383
0,Spam,Congratulations! You have won a free prize.,-0.042862,0.044704,0.011035,0.045548,0.010321,0.045686,0.036452,-0.049281,...,0.008697,0.010147,0.011390,-0.022467,0.078647,0.098466,0.020348,-0.063983,-0.091598,-0.019938
1,Ham,Your assignment deadline is Friday. Please sub...,-0.062948,0.062965,-0.016151,-0.009171,0.010431,-0.041878,-0.021588,0.002838,...,0.033412,0.043839,-0.038335,-0.073645,0.027106,0.020129,0.065411,0.050870,-0.015436,-0.019773
2,Spam,Get a free mobile phone now.,-0.034817,0.014303,0.139398,-0.024143,0.030147,-0.014429,-0.027990,0.033806,...,0.076763,-0.059857,0.022362,-0.018809,-0.041390,0.081300,0.003921,-0.025110,-0.050674,0.006333
3,Ham,Your class will start tomorrow at 9 AM.,-0.061452,-0.032167,0.001085,-0.009234,-0.015119,0.022941,-0.078902,0.045886,...,-0.020442,0.010816,-0.004519,-0.047471,-0.028190,0.016313,0.054123,0.066521,-0.087525,-0.025401
4,Spam,Claim your free gift card before the offer exp...,-0.088055,0.068895,0.058706,0.039981,0.029565,0.047461,0.040300,-0.009249,...,-0.070406,-0.011794,0.008473,0.034173,0.069620,0.036038,0.012606,-0.048348,-0.066960,-0.043483

In [21]:
# Final Assignment Validation

print("========== FINAL ASSIGNMENT CHECK ==========")

# 1. Dataset checks
assert len(df) == 10, "Dataset must contain 10 emails."
assert df["label"].value_counts().to_dict() == {
    "Spam": 5, "Ham": 5
}, "Dataset must contain 5 Spam and 5 Ham emails."

assert df[["label", "message"]].notna().all().all(), \
    "Dataset contains missing values."

print("1. Dataset: PASS")
print("2. Spam/Ham counts:")
print(df["label"].value_counts())

# 2. EDA checks
print("\n3. Dataset shape:", df.shape)
print("\n4. Dataset information:")
df.info()

# 3. Preprocessing checks
required_columns = [
    "lower_text",
    "tokens",
    "tokens_no_stopwords",
    "stemmed_words",
    "lemmatized_words",
    "processed_text"
]

for column in required_columns:
    assert column in df.columns, f"Missing column: {column}"

print("\n5. Text preprocessing: PASS")

# 4. Bag of Words check
assert X_bow.shape[0] == 10, "BoW must contain 10 email rows."
print("6. Bag of Words shape:", X_bow.shape)

# 5. Embeddings check
assert embeddings.shape == (10, 384), \
    "Expected 10 embeddings with 384 dimensions."

print("7. Embeddings shape:", embeddings.shape)

# 6. Display final results
print("\n8. Final dataset preview:")
display(df.head())

print("\nALL AUTOMATED CHECKS PASSED!")

========== FINAL ASSIGNMENT CHECK ==========
1. Dataset: PASS
2. Spam/Ham counts:
label
Spam    5
Ham     5
Name: count, dtype: int64

3. Dataset shape: (10, 8)

4. Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   label                10 non-null     object
 1   message              10 non-null     object
 2   lower_text           10 non-null     object
 3   tokens               10 non-null     object
 4   tokens_no_stopwords  10 non-null     object
 5   stemmed_words        10 non-null     object
 6   lemmatized_words     10 non-null     object
 7   processed_text       10 non-null     object
dtypes: object(8)
memory usage: 772.0+ bytes

5. Text preprocessing: PASS
6. Bag of Words shape: (10, 32)
7. Embeddings shape: (10, 384)

8. Final dataset preview:

,label,message,lower_text,tokens,tokens_no_stopwords,stemmed_words,lemmatized_words,processed_text
0,Spam,Congratulations! You have won a free prize.,congratulations! you have won a free prize.,"[congratulations, !, you, have, won, a, free, ...","[congratulations, free, prize]","[congratul, free, prize]","[congratulation, free, prize]",congratulation free prize
1,Ham,Your assignment deadline is Friday. Please sub...,your assignment deadline is friday. please sub...,"[your, assignment, deadline, is, friday, ., pl...","[assignment, deadline, friday, please, submit,...","[assign, deadlin, friday, pleas, submit, time]","[assignment, deadline, friday, please, submit,...",assignment deadline friday please submit time
2,Spam,Get a free mobile phone now.,get a free mobile phone now.,"[get, a, free, mobile, phone, now, .]","[get, free, mobile, phone]","[get, free, mobil, phone]","[get, free, mobile, phone]",get free mobile phone
3,Ham,Your class will start tomorrow at 9 AM.,your class will start tomorrow at 9 am.,"[your, class, will, start, tomorrow, at, 9, am...","[class, start, tomorrow]","[class, start, tomorrow]","[class, start, tomorrow]",class start tomorrow
4,Spam,Claim your free gift card before the offer exp...,claim your free gift card before the offer exp...,"[claim, your, free, gift, card, before, the, o...","[claim, free, gift, card, offer, expires]","[claim, free, gift, card, offer, expir]","[claim, free, gift, card, offer, expires]",claim free gift card offer expires

ALL AUTOMATED CHECKS PASSED!

## Conclusion

In this assignment, Natural Language Processing (NLP) techniques were applied to a dataset containing 10 email messages, including 5 Spam and 5 Ham emails.

The dataset was loaded into a Pandas DataFrame, and Exploratory Data Analysis (EDA) was performed using head(), shape, and info().

Text preprocessing included lowercasing, tokenization, stop word removal, stemming, and lemmatization.

Bag of Words (BoW) was used to convert the processed text into numerical features. Sentence Transformer embeddings were also generated using the all-MiniLM-L6-v2 model, producing a 384-dimensional vector for each email.

This assignment demonstrated how email text can be processed and represented numerically using NLP techniques. Although the dataset was labelled as Spam and Ham, a classification model was not trained in this assignment.